# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "juliateamo"
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
